# Tastecast store configuration (business parameters)
store:
  name: "Demo Bakery"
  lead_time_days: 2
  service_level: 0.95
  vendor_weekday: 0    # Monday
  restock_lot_size:
    apples: 300
    dough: 120

production:
  recipe:
    apples: 3
    dough: 1
  special_days: [3,4,5,6]   # Thu-Sun (0=Mon)
  special_boost_max_per_day: 5

forecast:
  forecast_horizon_days: 30
  forecast_year: 2026
