apiVersion: koyeb.com/v1
kind: Service
metadata:
  name: tastecast-backend
spec:
  type: web
  instance:
    cpu: 0.25
    memory: 512MB
  regions:
    - fra  # Frankfurt (EU) - you can change this to your preferred region
  scaling:
    min: 1
    max: 3
  ports:
    - port: 8000
      protocol: http
  environment:
    - name: FLASK_ENV
      value: production
    - name: PORT
      value: "8000"
    - name: PYTHONPATH
      value: /app
  healthcheck:
    path: /api/health
    interval: 30s
    timeout: 10s
    retries: 3
  volumes:
    - name: artifacts
      path: /app/artifacts
      type: temporary
    - name: uploads
      path: /app/uploads
      type: temporary
    - name: beta-signups
      path: /app/beta_signups
      type: temporary
